# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        cache_photos:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    cache: cache_photos

    filter_sets:

        miniature:
            quality: 50
            filters:
                scale:
                    dim: [280, 280]

        list:
            quality: 50
            filters:
                scale:
                    dim: [225, 150]

        show:
            quality: 80
            filters:
                scale:
                    dim: [1000, 1000]

        home:
            quality: 100
            filters:
                scale:
                    dim: [1000, 1000]

        icon:
            quality: 100

        expo:
            quality: 50
            filters:
                scale:
                    dim: [250, 250]